/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTesterForm: typeof import('./src/components/form/AddTesterForm.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    DefaultHeader: typeof import('./src/components/DefaultHeader.vue')['default']
    ForgotPwForm: typeof import('./src/components/form/ForgotPwForm.vue')['default']
    LoginForm: typeof import('./src/components/form/LoginForm.vue')['default']
    ModalWrap: typeof import('./src/components/ModalWrap.vue')['default']
    OrgotPwForm: typeof import('./src/components/form/orgotPwForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideHeader: typeof import('./src/components/SideHeader.vue')['default']
    SwList: typeof import('./src/components/list/SwList.vue')['default']
    SwVersionItem: typeof import('./src/components/list/SwVersionItem.vue')['default']
    SwVersionList: typeof import('./src/components/list/SwVersionList.vue')['default']
    TestStatusForm: typeof import('./src/components/form/TestStatusForm.vue')['default']
    UserList: typeof import('./src/components/list/UserList.vue')['default']
  }
}
