/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddDeployForm: typeof import('./src/components/form/AddDeployForm.vue')['default']
    AddJenkinsForm: typeof import('./src/components/form/AddJenkinsForm.vue')['default']
    AddMaintainerForm: typeof import('./src/components/form/AddMaintainerForm.vue')['default']
    AddTesterForm: typeof import('./src/components/form/AddTesterForm.vue')['default']
    AddTestUnitForm: typeof import('./src/components/form/AddTestUnitForm.vue')['default']
    AddUserForm: typeof import('./src/components/form/AddUserForm.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BoardRequestList: typeof import('./src/components/list/BoardRequestList.vue')['default']
    CommentItem: typeof import('./src/components/list/CommentItem.vue')['default']
    CommentList: typeof import('./src/components/list/CommentList.vue')['default']
    CommentReactionList: typeof import('./src/components/list/CommentReactionList.vue')['default']
    DeployList: typeof import('./src/components/list/DeployList.vue')['default']
    ForgotPwForm: typeof import('./src/components/form/ForgotPwForm.vue')['default']
    HistoryList: typeof import('./src/components/list/HistoryList.vue')['default']
    JenkinsList: typeof import('./src/components/list/JenkinsList.vue')['default']
    LoginForm: typeof import('./src/components/form/LoginForm.vue')['default']
    ModalWrap: typeof import('./src/components/ModalWrap.vue')['default']
    NewBoardForm: typeof import('./src/components/form/NewBoardForm.vue')['default']
    NewServiceForm: typeof import('./src/components/form/NewServiceForm.vue')['default']
    NewVersionForm: typeof import('./src/components/form/NewVersionForm.vue')['default']
    ResetPwForm: typeof import('./src/components/form/ResetPwForm.vue')['default']
    RichEditor: typeof import('./src/components/RichEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SideHeader: typeof import('./src/components/SideHeader.vue')['default']
    SwList: typeof import('./src/components/list/SwList.vue')['default']
    SwVersionItem: typeof import('./src/components/list/SwVersionItem.vue')['default']
    SwVersionList: typeof import('./src/components/list/SwVersionList.vue')['default']
    TempSocketInfo: typeof import('./src/components/TempSocketInfo.vue')['default']
    TestListChart: typeof import('./src/components/list/TestListChart.vue')['default']
    TestListChips: typeof import('./src/components/list/TestListChips.vue')['default']
    TestStatusForm: typeof import('./src/components/form/TestStatusForm.vue')['default']
    UnitTestList: typeof import('./src/components/list/UnitTestList.vue')['default']
    UserList: typeof import('./src/components/list/UserList.vue')['default']
  }
}
