# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [20.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Npm -v
        run: npm -v

      - name: build vue files
        working-directory: ./
        run: |
          npm install
          npm run build

      - name: zip file
        run: zip -r qaVue.zip ./dist ./scripts ./appspec.yml ./ecosystem.config.js
        # ./package.json

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./qaVue.zip s3://hkqa-build-bucket/deploy/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --file-exists-behavior OVERWRITE
          --application-name hkqavue
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name HKQAGROUP
          --ignore-application-stop-failures
          --s3-location bucket=hkqa-build-bucket,bundleType=zip,key=deploy/qaVue.zip
